"""Add password reset tokens table

Revision ID: 4d140a8bbf65
Revises: 5f57755af9a0
Create Date: 2026-01-29 12:40:37.523692

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '4d140a8bbf65'
down_revision = '5f57755af9a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
